### PR TITLE
Alternative version of wavy_dude

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
As per your request, an alternative drawing for the wavy guy!

image

### CODE REVIEW

**Comment by martin-henz** [comment]
At the moment, the curvy wave pictures are in contradiction with the following exercises:

Exercise 2.49 (d) (page 123): A curvy wave painter cannot be composed of line segments.

Exercise 2.52 (a) (page 126): This is clearly meant as adding line segments to the wave picture.

My suggestion is that we get back to the original wave picture and draw it as a primitive rune in the RUNES library.

**Comment by martin-henz** [comment]
(converted to "draft" because discussion on-going)

**Comment by TobiasWrigstad** [comment]
> My suggestion is that we get back to the original wave picture and draw it as a primitive rune in the RUNES library.

As in the original picture from SICP 2e? So basically I redraw this picture with straight lines?

**Comment by martin-henz** [comment]
Yes, straight lines is clearly deliberate design choice of SICP 2e. If you draw the wave picture as part of the RUNES library, the advantage would be that we can generate all the drawings with a Source program. See: https://github.com/source-academy/frontend/blob/master/public/externalLibs/graphics/webGLrune.js
basically we would need to add a makeWave function there.

The additional advantage of this would be that users of the interactive version of SICP JS can play with the wave figure and generate the textbook designs.

**Comment by TobiasWrigstad** [comment]
Great. I had missed that the straight lines were deliberate. I'll redo this then, but probably not tonight. It took a bit of time to do :)

**Comment by martin-henz** [comment]
Yes, must have taken A LOT of time. Sorry! Thanks for taking another look at this.

**Comment by TobiasWrigstad** [comment]
Haha, this was my fault. I should have realised it.

**Pull request closed without merging**
