### PR TITLE
Making cloud black on white as per Julie's request

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
Julie said: 
> Tobias, I am concerned that there could be a printing issue with
> fig 4.4, p.349.  The factorial function is in a light gray cloud
> with no outline.  In SICP (p.384) there was an outline.

> If the gray prints too lightly, the cloud may vanish, and factorial
> won't be enclosed as a "thing."  But if you make it darker and it
> prints too dark, the contrast could be too low.
> Is it possible to ouline it as in SICP?

### CODE REVIEW

**Review by martin-henz — CHANGES_REQUESTED** [review]
Can we have the lines not-crosssing, as in SICP?

Screenshot 2021-11-15 at 1 28 54 AM

**Comment by TobiasWrigstad** [comment]
I've fixed that now!

**Comment by TobiasWrigstad** [comment]
Fixes #698

**Review by martin-henz — APPROVED** [review]
This is good now!

**Pull request merged**
