### PR TITLE
updated epub version

### PR DESCRIPTION
**Pull request by jolynnn8D**

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
@jolynnn8D I am not able to build this. When I do `make epub`, I see the following: 

```
pandoc:
Error at "source" (line 1, column 15):
unexpected "["
expecting letter or lf new-line
\documentclass[a4paper, 12pt]{report}
              ^
CallStack (from HasCallStack):
  error, called at src/Text/Pandoc/Error.hs:66:13 in pandoc-1.19.2.4-HbfKWUyODESBIy0vGktOwX:Text.Pandoc.Error
```

My version of pandoc is 
```
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
```

Furthermore, in the `Makefile` there is this: 

```
epub:
	npm start epub && npm start epub
	cd latex && pandoc sicpjs.tex --listings -o sicp.epub --toc --epub-chapter-level=3 --number-sections --css ../css/sicp.css --epub-cover-image=../rails/public/chapters/coverpage.png
```

The first line seems to run the Node script twice if first run is successful. Why is this?

**Comment by martin-henz** [comment]
@jolynnn8D I tried to look at this PR. I'm getting this, possibly because of wrong pandoc version?

```
r-14-121-25-172:sicp henz$ make epub
npm start epub

> sicpxml2latex@1.0.0 start /Users/henz/Documents/source-academy/sicp
> babel-node ./nodejs/index.js "epub"

using parsetype epub
setup snippets
setup snippets done

chapter1/chapter1.xml
chapter3/chapter3.xml
chapter2/chapter2.xml
WARNING, EXAMPLE not found: linear_combination_example

chapter4/chapter4.xml
others/02foreword02.xml
others/03prefaces03.xml
others/04acknowledgements04.xml
others/97references97.xml
others/98indexpreface98.xml
others/99making99.xml
chapter1/section1/section1.xml
chapter1/section1/subsection1.xml
chapter1/section1/subsection2.xml
WARNING, REQUIRES not found: var_size

WARNING, REQUIRES not found: var_size

WARNING, REQUIRES not found: var_size

... many more warnings, and eventually:

chapter4/section2/subsection3.xml
cd latex && pandoc sicpjs.tex --listings -o sicp.epub --toc --epub-chapter-level=3 --number-sections --metadata=title:"Structure and Interpretation of Computer Programs (JavaScript Adaptation)" --css ../css/sicp.css --epub-cover-image=../rails/public/chapters/coverpage.png
pandoc: 
Error at "source" (line 1, column 15):
unexpected "["
expecting letter or lf new-line
\documentclass[a4paper, 12pt]{report}
              ^
CallStack (from HasCallStack):
  error, called at src/Text/Pandoc/Error.hs:66:13 in pandoc-1.19.2.1-JIeRA5EnQv74mk86CvVbbp:Text.Pandoc.Error
make: *** [epub] Error 1
r-14-121-25-172:sicp henz$ 
```

https://github.com/source-academy/sicp/wiki/EPUB-Edition

**Comment by martin-henz** [comment]
Can we update our wiki, to document what our requirements are, for example regarding the pandoc version? See: https://github.com/source-academy/sicp/wiki/EPUB-Edition

**Comment by jolynnn8D** [comment]
required version is pandoc 2.7.3. i have updated the wiki page accordingly.

**Comment by TobiasWrigstad** [comment]
Subsumed by #135.

**Pull request closed without merging**
