### PR TITLE
Pretty PDF with Vector Images (SVGs)

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
This PR merges the two branches `pretty-pdf` and `svg` and corrects multiple minor issue with both branches, including an indexing bug fixed by @gerhean. In addition to fixes it:

- Scales down images by 0.2 default
- Fixes kerning issue with fonts without breaking column alignment
- Most figures sizes are OK (IMO) but some work remains there

What is missing is to give credit to the original creators of the SVGs (over at https://github.com/sarabander/sicp). Incidentally, it seems we chose similar fonts although I based mine on acmart.cls. I don't know where that belongs in this document. 

(I probably need to play some catching up with this branch before it can merge too.)

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
EDIT: turned out the catching up was minimal.

**Comment by TobiasWrigstad** [comment]
Hmm. Quite unclear why there are so many commits attached to this PR. I must have messed something up.

**Comment by gerhean** [comment]
Fixed some minor bugs.

**Comment by TobiasWrigstad** [comment]
Interesting — I could not reproduce the OOM on my two LaTeX installations.

**Pull request merged**
