### PR TITLE
Equation alignment

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
Work in progress -- feel free to push to this branch

### CODE REVIEW

**Comment by martin-henz** [comment]
What do you mean by "work in progress"? What is missing?

I see there are still a few align* left:

henz@workshops-MacBook-Pro sicp % grep -r "{align\*}" xml
xml/chapter1/section2/subsection1.xml:      \begin{align*}
xml/chapter1/section2/subsection1.xml:      \end{align*}
xml/chapter2/section3/subsection2.xml:      \begin{align*}
xml/chapter2/section3/subsection2.xml:      \end{align*}
xml/chapter2/section4/subsection1.xml:      \begin{align*}
xml/chapter2/section4/subsection1.xml:      \end{align*}
xml/chapter3/section5/subsection2.xml:    \begin{align*}
xml/chapter3/section5/subsection2.xml:    \end{align*}

Is that a problem?

**Comment by martin-henz** [comment]
Fixes #470

**Comment by TobiasWrigstad** [comment]
No there is no problem. Because there is not a single best solution, I am mixing two and making sure that the tiny difference in indentation is not visible by appearing next to each other on a single spread.

**Comment by martin-henz** [comment]
Ah, I see.

**Comment by martin-henz** [comment]
Done some small fixes in 3.5.4 and 4.4.2, to make them look like equations and align them. Not sure if you like it @TobiasWrigstad can you take a look?

**Comment by martin-henz** [comment]
@TobiasWrigstad can you check? see above.

**Pull request merged**
