### PR TITLE
Adds a permalink capability following #120

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
- Clicking a `<p>..</p>` tag copies the permalink
- Visual queues using Jquery-ui (new dependency), highlight + message box
- Format of permalink is http://localhost:3000/chapters/6#p5 to get to 5th paragraph of Chapter 6

Addresses #120 although it does not use right-click (which can be fixed, but then people will not see it).

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
Update to this PR will come in 10 minutes -- I spotted a violation of HTML nesting rules

**Comment by martin-henz** [comment]
I love this feature! I think it will improve the utilization of the textbook a lot because we can link directly into the specific paragraphs.

Played with Chapter 2. The copying of permalinks works for the intro of Chapter 2, but does not work for Section 2.1.

**Comment by TobiasWrigstad** [comment]
Thanks! I missed adding a hook to the function that dynamically loads content. Will fix after lunch.

**Comment by TobiasWrigstad** [comment]
We might also consider adding the same for headings

**Comment by TobiasWrigstad** [comment]
Please squash on merge!

**Comment by martin-henz** [comment]
This is amazing!

**Pull request merged**
