### PR TITLE
Julie tobias pass 14 11

### PR DESCRIPTION
**Pull request by TobiasWrigstad**

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
@martin-henz This does not contain pagination of index. That will follow "soon".

**Comment by martin-henz** [comment]
Just checking: this is ready for review and after that merging, right?

I'm starting the review now, building the PDF.

**Comment by TobiasWrigstad** [comment]
Yes, indeed!

**Comment by TobiasWrigstad** [comment]
Julie and I have looked at these together and proof-read, so hopefully smooth sailing!

**Comment by TobiasWrigstad** [comment]
(We mostly wanted you to know what had changed)

**Review by martin-henz — APPROVED** [review]
all good

**Pull request merged**
