### PR TITLE
Cleaning up PDF generation

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
TODO:
[x] Remove all superflous images
[x] Find SVGs with merge conflicts
[ ] Ask Martin to test on his machine

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
@martin-henz Can you see if this PR works for you with respect to generating PDFs from svgs? I have crafted a Makefile to handle the PDF generation that could be part of the workflow as it only requires building PDFs whose correspondings SVGs have a newer date.

**Comment by TobiasWrigstad** [comment]
I have also tried to remove tons of image files that are no longer used.

**Comment by martin-henz** [comment]
> I have also tried to remove tons of image files that are no longer used.

great!

**Comment by martin-henz** [comment]
So yes, with my inkscape I still cannot generate the pics, but that doesn't matter. Please go ahead and merge if this works for you.

**Pull request merged**
