### PR TITLE
Normalised spaces; page breaks in the right places (and avoiding)

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
Addresses #529 

Look at the diff. There's lots happening here. Many snippets have an empty line removed so that the automatic "on to insert page break hear" elaboration works on them.

### CODE REVIEW

**Review by martin-henz — CHANGES_REQUESTED** [review]
Looks fine.

I'll run the removal of the newlines in 2.2.3 by Julie, to be sure she explicitly oks it.

**Review by martin-henz — COMMENTED** [review]
This PR is quite confused. It mixes two separate issues, which isn't good practice.

The first issue (normalized spaces) looks fine.

The second issue: page breaks in the right places:

SICP never breaks pages in programs. I think we should follow that. I think Julie feels strongly about this. I think we should never automatically break pages within programs. If we need to break pages in programs, we should do that explicitly and manually, when we finish the book. Or maybe I missed or forgot some emails. Have you discussed this with Julie?

**Comment by TobiasWrigstad** [comment]
I am not so sure I agree the PR is confused. The space issue I was chasing led to propagating effects, where the book grew in page numbers by 6 pages so I had to investigate that. If you like I can turn this into 3 separate PR's which can all be reviewed individually, but whose combination should be considered when doing so. 

I should probably have explained this better -- everything was probably "obvious" to me after so many hours of working on this issue. 

Here are the three sub-issues:
1) the handling of spacing between "subsnippets" that we would like to be adjacent, including how we allow page breaks between these or not
2) the use of postpadding="no" on snippets adjacent to elements that come with built-in before padding (like a heading) 
3) consistent spacing between related functions, including how we allow page breaks between these or not

Julie has said that page breaks in code is only permissible when the break will occur in a logical place, and preferably in that case when pages are facing. This is how SICP did it (see e.x. p 319-320 or 306-307 and 74-75 for examples of programs / snippets being spread over 2 pages). 

In the current version of the book, we sometimes have a thin space between functions and in other places not. There is no logic behind this as far as I can tell, and this is what 3) addresses. This also *optionally allows* page breaking between all functions except in the places where we want to present functions with a long space between them, e.g. when presenting two versions of a function together etc. 

My proposal is to disable page breaks in the places where we don't want them. This will not be many places to look at. Optionally, we could turn on page breaks where we wanted them. Right now, we do the first, but we can easily change to the second. 

*If you prefer, I can split this into 3 separate PR's for each sub-issue, and turn off the feature that (reluctantly) allows LaTeX to insert a page break between top-level functions.*

**Comment by martin-henz** [comment]
There are five independent things in this PR. Let's proceed like this:

(1) Space between prompt-input-output (you call them subsnippets): No need for PR: just make the change and drop a note to Julie an me that points to the places that have changed

(2) Allow page breaks between subsnippets within a snippet (prompt-input-output): I'd say no. These belong together.

(3) the use of postpadding="no" on snippets adjacent to elements that come with built-in before padding (like a heading): Just make the change and drop a note to Julie and me that points to the places that have changed

(4) consistent spacing between related functions: Julie went through the whole book and endorsed our current placement of newlines. If you think it's not consistent, let's discuss. What do you mean by "consistent" and what do you want to change? Julie should be involved in this discussion. You may want to make a PR and send Julie and me a version where you have made the changes, and point us to the places that have changed.

(5) how we allow page breaks within programs

You say:

"My proposal is to disable page breaks in the places where we don't want them. This will not be many places to look at. Optionally, we could turn on page breaks where we wanted them. Right now, we do the first, but we can easily change to the second."

I think page breaks within snippets should be the exception and we should deliberate each case specifically: Does it lie on opposing pages? How big is the program? How complex is the argument? How do the different functions within the snippet relate to each other?

So I strongly prefer the second option: Let's prevent page breaks within snippets, and let's have a mechanism that explicitly allows a page break at explicitly specified places.

**Comment by TobiasWrigstad** [comment]
> (1) Space between prompt-input-output (you call them subsnippets): No need for PR: just make the change and drop a note to Julie an me that points to the places that have changed

All places in the book that uses the PROMPT-INPUT scheme is affected by this. But I'll write that in an email. Pushed this change now.

**Comment by TobiasWrigstad** [comment]
> (3) the use of postpadding="no" on snippets adjacent to elements that come with built-in before padding (like a heading): Just make the change and drop a note to Julie and me that points to the places that have changed

I have pushed this. Will figure out how to point to places that have changed as page numbers aren't that stable right now.

**Comment by TobiasWrigstad** [comment]
> (2) Allow page breaks between subsnippets within a snippet (prompt-input-output): I'd say no. These belong together.

There is now a no page break macro in the macro between such snippets trying to get LaTeX to avoid this.

**Comment by TobiasWrigstad** [comment]
I've isolated everything related to 4). I don't recall that email but I'll try to dig it up. If you know which one that would be helpful.

**Comment by TobiasWrigstad** [comment]
5) Page-breaks are opt-in.

**Pull request closed without merging**
