### PR TITLE
Addresses comments from Julie about white pages and acknowledgements

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
Don't merge yet until I've checked with Julie.

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
(Rebased on master)

**Comment by TobiasWrigstad** [comment]
Fine to merge now (after review ofc). All good with spaces and no spilling of Perlis' signature is no longer orphaned.

**Review by martin-henz — CHANGES_REQUESTED** [review]
This page should be empty, I think:

Screenshot 2021-06-11 at 9 48 00 AM

Should it be "for" or "from"?

Screenshot 2021-06-11 at 9 49 49 AM

Screenshot 2021-06-11 at 9 49 55 AM

**Comment by TobiasWrigstad** [comment]
Ah. Something must have been messed up. The package that I included to fix this was lost in the merge somehow. 

Building now to verify and then I'll push.

**Comment by TobiasWrigstad** [comment]
You are right that there is a possible inconsistency. With respect to for/from -- I think "from" is correct when we are talking about acks which are actually taken _from_ another book. And our acks are _for_ our book. I kept the _from_ because that had not been (AFAIK) questioned by Julie, but _from_ did not seem right for our acks. 

Maybe defer to Julie on what's right?

**Comment by TobiasWrigstad** [comment]
Addressed the non-empty page now.

**Pull request merged**
