### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
Ready to merge 

Please check that the new exercises are still correct. I had some massive merge problems as I was replaying multiple commits to them during rebasing.

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
Not ready to merge!

**Comment by TobiasWrigstad** [comment]
Because of the error on p 384 you found

**Comment by martin-henz** [comment]
ok

**Comment by martin-henz** [comment]
A file is missing:

[498])) (./chapter5/section4/section4.tex

LaTeX Warning: File `{img_original/chip-cropped}.png' not found on input line 5
.

**Review by martin-henz — COMMENTED** [review]
all good

**Review by martin-henz — APPROVED** [review]

**Pull request merged**
