### PR TITLE
Adds some space between prompt/input/output snippets

### LINKED ISSUE #497: PDF: space between prompt-input-output in program snippets
I don't think we have fixed this issue yet.
I think Tobias made the input line (let's call it "prompt") to be separated from the programmer's input by space that is about one line tall.
On the other hand, there is no space that separates the programmer's input from the output of the program.
My suggestion:
(1) Prompt  (in italics as it currently is)
(2) a little space
(3) Programmer's input (normal mono font)
(4) the same little space as in (2)
(5) Output (in italics as it currently is)

Context:

from: | Julie Sussman&nbsp;&lt;jems@csail.mit.edu&gt;
-- | --
reply-to: | jems@alum.mit.edu
to: | Tobias Wrigstad &lt;tobias.wrigstad@it.uu.se&gt;
cc: | Martin Henz &lt;henz@comp.nus.edu.sg&gt;
date: | 27 Apr 2021, 10:56
subject: | SV: SICP JS formatting glitches and issues

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
Fixes #497

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
Finally got around to this. (The edit is small but boy is the processSnippet code ripe for a total rewrite (after the MIT deadline).)

Please have a look to see if you like it. 

It follows your suggestion from #497. You can tweak the space by changing this line in `latexContent.js`
```
\\newcommand{\\PromptInputOutputSpace}{{\\vskip 0.8em}\\noindent}
```
Don't use pt as we want the space to be proportional with the size of the font (smaller in exercises, for example).

The PR affects 62 places in the book. If you want to see these places, you can for example do 
```
\\newcommand{\\PromptInputOutputSpace}{{\\vskip 0.8em XXX}\\noindent}
```
which will add an `XXX` to all these places so you can search for them easily.

**Review by martin-henz — CHANGES_REQUESTED** [review]
The space before the JAVASCRIPT_OUTPUT isn't always inserted:

Screenshot 2021-06-11 at 10 41 30 AM

Screenshot 2021-06-11 at 10 40 38 AM

...but strangely, sometimes it is inserted:

Screenshot 2021-06-11 at 10 38 16 AM

**Comment by TobiasWrigstad** [comment]
Hm. This adds *lots* of blank lines all over the place (180+ cases). For example, look at the consequence for page 4. 

I wonder what is the right cause of action.

**Comment by TobiasWrigstad** [comment]
I'm pushing the change so you can see for yourself. Maybe one way is to reduce the number of space that we insert by say 50%. 

Another option is to distinguish cases where there are long definitions entered and evaluated vs. single lines and output.

**Comment by martin-henz** [comment]
Yes, a full line is way too much space. In the unformatted version, I had less than half a line of extra space. I'll play with this and commit a version that looks right to me. then we an discuss, also with Julie.

**Pull request merged**
