### PR TITLE
Support line break in inline code

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
Adding an `@` in JAVASCRIPTINLINE tag allows that place to have a line break. Should only be visible in PDF.

### CODE REVIEW

**Review by martin-henz — CHANGES_REQUESTED** [review]
The PR currently doesn't build. Can you take a look?

chapter2/chapter2.xml

/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:470

      } else if (node.firstChild.search("@") >= 0) {

                                 ^


TypeError: node.firstChild.search is not a function

**Comment by TobiasWrigstad** [comment]
I've updated this PR to fix the problem and also with improved line breaking for Chapter 5.

**Comment by martin-henz** [comment]
The branch has diverged from master. @TobiasWrigstad can you fix this?

```
henz@workshops-MacBook-Pro sicp % git checkout master  
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
henz@workshops-MacBook-Pro sicp % git pull
Already up to date.
henz@workshops-MacBook-Pro sicp % git checkout line-break-in-inline-code
Switched to branch 'line-break-in-inline-code'
Your branch and 'origin/line-break-in-inline-code' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
henz@workshops-MacBook-Pro sicp % git pull
Auto-merging xml/chapter5/section5/subsection2.xml
Auto-merging xml/chapter5/section4/subsection2.xml
Auto-merging javascript/parseXmlLatexSplit.js
CONFLICT (content): Merge conflict in javascript/parseXmlLatexSplit.js
Auto-merging javascript/parseXmlLatex.js
CONFLICT (content): Merge conflict in javascript/parseXmlLatex.js
Auto-merging javascript/parseXmlJson.js
CONFLICT (content): Merge conflict in javascript/parseXmlJson.js
Auto-merging javascript/parseXmlHtml_split.js
CONFLICT (content): Merge conflict in javascript/parseXmlHtml_split.js
Auto-merging javascript/parseXmlHtml.js
CONFLICT (content): Merge conflict in javascript/parseXmlHtml.js
Automatic merge failed; fix conflicts and then commit the result.
henz@workshops-MacBook-Pro sicp % 
```

**Comment by TobiasWrigstad** [comment]
Ah, sorry. OFC. Fixed now!

**Comment by martin-henz** [comment]
I'm getting a number of issues, currently:

(1) install fails

* clean clone
* yarn install
gives me
```
henz@r-225-121-25-172 sicp % yarn install
yarn install v1.22.10
warning ../package.json: No license field
warning ../../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "sicp > xmlhttprequest-ts@1.0.1" has unmet peer dependency "@angular/common@>= 5.0.0".
warning "sicp > xmlhttprequest-ts@1.0.1" has unmet peer dependency "@angular/core@>= 5.0.0".
[4/4] 🔨  Building fresh packages...
[1/3] ⢀ gl
[2/3] ⢀ core-js
error /Users/henz/Documents/source-academy/sicp/node_modules/gl: Command failed.
Exit code: 1
```

(2) yarn pdf fails (related to (1)?)

```
chapter5/section1/subsection1.xml
chapter5/section1/section1.xml
/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:470
      } else if (node.firstChild.data.search("@") >= 0) {
                                      ^

TypeError: Cannot read property 'search' of undefined
    at Object.JAVASCRIPTINLINE (/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:558:39)
    at processTextLatex (/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:653:5)
    at recursiveProcessTextLatex (/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:669:3)
    at recursiveProcessTextLatex (/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:670:10)
    at processTextLatex (/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:659:7)
    at recursiveProcessTextLatex (/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:669:3)
    at recursiveProcessTextLatex (/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:670:10)
    at recursiveProcessTextLatex (/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:670:10)
    at recursiveProcessTextLatex (/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:670:10)
    at recursiveProcessTextLatex (/Users/henz/Documents/source-academy/sicp/javascript/parseXmlLatex.js:670:10)
error Command failed with exit code 1.
```

**Comment by martin-henz** [comment]
Not really fixed. Various problems. See PR.

-martin
http://www.comp.nus.edu.sg/~henz

**Review by martin-henz — APPROVED** [review]

**Pull request merged**
