### PR TITLE
Started to make a pass over Chapter 5

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
Pushing WIP here so that interested parties can follow along

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
I have now updated the code in §5.4 (§5.3 skipped for now). 

I have based the working program on https://github.com/source-academy/source-programs/pull/39 and made some very minor changes to get closer to the original. 

There is a hack and some minor deviations in the code that needs addressing.

**Comment by TobiasWrigstad** [comment]
I am getting some XML linting errors e.g. when inside a `<JAVASCRIPT_RUN>` tag I use a `<` operator... Is there a way around this?

**Comment by martin-henz** [comment]
Yes, < and > need to be represented in XML as &lt; and &gt;. XML parsers seem to differ in how strictly they enforce this.

**Comment by martin-henz** [comment]
> I am getting some XML linting errors e.g. when inside a `<JAVASCRIPT_RUN>` tag I use a `<` operator... Is there a way around this?

Yes, < and > need to be represented in XML as < and >. XML parsers seem to differ in how strictly they enforce this.

**Comment by martin-henz** [comment]
> > I am getting some XML linting errors e.g. when inside a `<JAVASCRIPT_RUN>` tag I use a `<` operator... Is there a way around this?
> 
> Yes, < and > need to be represented in XML as < and >. XML parsers seem to differ in how strictly they enforce this.

Also && needs to be &amp;&amp;. (there are some of those in 5.5.)

**Pull request merged**
