### PR TITLE
Finalising images

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
Finalizing all images EXCEPT 2.9-2.12, 2.14 (Rogers and wavy). 

This includes: 
- Colors of lines
- Font sizes
- Figure sizes (left unchanged except for relative size changes inside wrt text) 

Questions/comments:

SICP 2e has all the text of Figure 2.15 in code font, we have it all in
text font. Since the names don't necessarily refer to elements in code,
but concepts, I feel text font is better. Input?

Figure 3.31 might have become a little too tight in the leftmost
triangle -- or will it do? 

I left a ... in Figure 5.14 NOT as an ellipsis because it wasn't code
and it looked terrible with an ellipsis character.

### CODE REVIEW

**Comment by martin-henz** [comment]
For figure 2.15: That's a huge improvement. SICP's picture is really ugly.

However, frame1 and frame2 don't appear in the text in this way. They shouldn't be code font, because SICP didn't say edge1-frame. I think we should render the words as in the formula:

Origin(Frame)+x· Edge1 (Frame)+y· Edge2 (Frame)

That means:
frame => Frame (three times)
edge1 => Edge1 (with subscript 1)
edge2 => Edge2 (with subscript 2)
origin => Origin

**Comment by martin-henz** [comment]
> I left a ... in Figure 5.14 NOT as an ellipsis because it wasn't code
> and it looked terrible with an ellipsis character.

Looks fine now.

**Comment by martin-henz** [comment]
> Figure 3.31 might have become a little too tight in the leftmost
> triangle -- or will it do?

It's fine.

**Comment by martin-henz** [comment]
Screenshot 2021-07-22 at 8 15 55 AM

base e and exponent iA are too close together

**Comment by martin-henz** [comment]
Screenshot 2021-07-22 at 8 19 07 AM

Can we use the same font as in the text?

**Comment by martin-henz** [comment]
Screenshot 2021-07-22 at 8 23 10 AM

A couple of pixels missing from the right edge.

**Comment by martin-henz** [comment]
Screenshot 2021-07-22 at 8 37 02 AM

The horizonal line should connect to the dot, see SICP.

**Comment by TobiasWrigstad** [comment]
Addressed everything now! Please take a look to see it is OK.

**Comment by TobiasWrigstad** [comment]
Before this is merged I will address Julie's comment on the ellipsis!

**Comment by TobiasWrigstad** [comment]
Ellipses done!

**Review by martin-henz — APPROVED** [review]
All good

**Pull request merged**
