### PR TITLE
Left justification of captions

### PR DESCRIPTION
**Pull request by TobiasWrigstad**

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
Are you OK with this visual change?

**Comment by TobiasWrigstad** [comment]
Would you prefer coming up with a way to hyphenate (or reword) captions and keep them justified?

**Comment by martin-henz** [comment]
Here is the book compiled with this option:
[sicpjs.pdf](https://github.com/source-academy/sicp/files/6512487/sicpjs.pdf)

I have no issues with ragged-right captions. They look fine to me.

**Review by martin-henz — APPROVED** [review]
We reached a consensus that this is fine as a whole. Individual captions are addressed in a separate issue: #487

**Pull request merged**
