### PR TITLE
New test script using JavaScript

### PR DESCRIPTION
**Pull request by LuminousXLB**
I've got a new test script written in JavaScript.

It takes about 3 mins to run all the tests.
```
node scripts/test.js  185.89s user 2.59s system 91% cpu 3:25.32 total
```
But there's a test case which throws an error.

```
js_programs/chapter5/section3/subsection2/01_testing_5_3_2.js, expecting: [ 'ptr', 108 ]
Line 529: Name make_go_to_ef not declared.
```

And I cannot pass the test case using the original test script either.

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
When I run `node scripts/test.js`, I immediately see ```
0 test cases completed.
0 passed, 0 failed
``` Am I missing something? I have a hard time recreating the error above.

**Comment by Gopiandcode** [comment]
You need to run `yarn js` first to populate the `js_programs` folder with programs to test.

**Comment by Gopiandcode** [comment]
When I run the tests, I also get a couple additional failing cases due to a slow execution:
```
js_programs/chapter3/section5/subsection3/23_integral_1.js, expecting: 4.48499999999999
2
Line 386: Potential infinite recursion detected: stream_ref([ 2.4531000000000014,
() => {
  if (!already_run) {
    result = fun();
    already_run = true;
    return result;
  } else {
    return result;
  }
}], 78) ... stream_ref([ 2.475300000000001,
() => {
  if (!already_run) {
    result = fun();
    already_run = true;
    return result;
  } else {
    return result;
  }
}], 77) ... stream_ref([ 2.497600000000001,
() => {
  if (!already_run) {
    result = fun();
    already_run = true;
    return result;
  } else {
    return result;
  }
}], 76).
      If you are certain your program is correct, press run again without editing your 
program.
      The time limit will be increased from 1 to 10 seconds.
      This page may be unresponsive for up to 10 seconds if you do so.
```

Although this may have also been the case in the previous testing script as well and thus might warrant a separate issue?

**Comment by LuminousXLB** [comment]
> js_programs/chapter3/section5/subsection3/23_integral_1.js

Yes. This error comes out sometimes. But it can also pass somehow.
I'm really unfamiliar with SICP. Do you have any advice on that?

**Comment by martin-henz** [comment]
> > js_programs/chapter3/section5/subsection3/23_integral_1.js
> 
> Yes. This error comes out sometimes. But it can also pass somehow.
> I'm really unfamiliar with SICP. Do you have any advice on that?

I need to edit the test case to be safely within the allotted time. Will try to find time for this.

**Comment by TobiasWrigstad** [comment]
Ah ofc! Thanks!

**Comment by TobiasWrigstad** [comment]
After a *long* chase to resolve dependencies, I have resolved this locally. Now I instead get a crash somewhere deep in the test:
```
Line 107: Error: tail(xs) expects a pair as argument xs, but encountered 0
```
I don't have the ability to debug this error right now because of other priorities so maybe we can file an issue?

**Comment by LuminousXLB** [comment]
I've just updated the script. Now there's only one failing test case.

``` 
js_programs/chapter5/section3/subsection2/01_testing_5_3_2.js, expecting: [ 'ptr', 108 ]
Line 107: Error: tail(xs) expects a pair as argument xs, but encountered 0
578 test cases completed.
577 passed, 1 failed
```

**Review by martin-henz — APPROVED** [review]
Good work. Nice to get rid of that shell script! Much faster now.

**Pull request merged**
