### PR TITLE
epub

### PR DESCRIPTION
**Pull request by jolynnn8D**
unsure of how to accommodate two node.js versions for now.
currently running the epub by changing the directory in the package.json file.
Screenshot 2019-07-09 at 2 29 47 AM

### CODE REVIEW

**Comment by martin-henz** [comment]
> unsure of how to accommodate two node.js versions for now.
> currently running the epub by changing the directory in the package.json file.
> Screenshot 2019-07-09 at 2 29 47 AM

Yes, that's a good question. Can you describe how you would, using your branch, generate first the EPUB version, and then the PDF version?

In your branch, what changes do you need to make, in order to get the PDF?

From that, we will be able to see how to generate both versions in the same system.

**Comment by martin-henz** [comment]
At the moment, you dont seem to refer to your new folder nodejs_epub in the Makefile or in package.json. So my question: How do you generate the EBUB version, using your branch?

**Comment by jolynnn8D** [comment]
I didn’t add my package.json file to the pull request. At the moment, changing the directory of the start script in the package.json file to nodejs_epub and running make epub generates the epub. Changing it back to nodejs and running make pdf generates the pdf. Both the pdf and the epub will then be available in the latex folder.

**Comment by martin-henz** [comment]
I see. So now, how would you improve the situation?

We would like to do the following:

> make all

As a result, the PDF, EPUB and WEB versions are made. 

> make install

All these versions are uploaded to the server. Take a look at the Makefile, and at package.json, and at the overall folder structure. Do you see how we can achieve full automation?

Once everything is right, I should be able to just go:

> make install

and the entire textbook (PDF, EPUB, WEB) is generated and uploaded to the server.

**Comment by martin-henz** [comment]
Wow, that's a creative solution: Two separate package.json files!

That would have pros and cons, regarding overall team work and efficiency. Can you think long-term? What tasks will arise as we continue to collaborate, over the coming months (and, with different students) years? 

To prepare for the meeting, you might want to explore alternatives to this design, and think about their pros and cons on the long run.

**Pull request closed without merging**
